### ISSUE TITLE
Update schema.json

### ISSUE THREAD

**Issue by orasul** [CsteerDevops1/wiki-framework#10]
Let's assume we should have following properties:
id - unique number
name - string
synonyms - an array of strings
description - text description - string
relations with other elements - an array of strings
tags - set of words.
Optional:
photo - type img/*
video - type video/*
audio - type audio/*

**Comment by takikokos** [comment]
@orasul  Should i do this in old schema branch or create new?

**Comment by orasul** [comment]
If old branch is removed You should create the new one. Otherwise - it doesn't matter.

**Comment by takikokos** [comment]
Database document schema.json can be found [here](https://github.com/CsteerDevops1/wiki-framework/blob/develop/coreService/schema.json)
