### ISSUE TITLE
Add translation to other languages to schema.

### ISSUE THREAD

**Issue by orasul** [CsteerDevops1/wiki-framework#19]
Each word has several translations to other languages. I'd suggest to use English words in DB and have additional property - Russian translation:
ball - RU ["мяч","шар","бал","шарик"], etc.
This should be optional. Please add to schema.

**Comment by takikokos** [comment]
Database document schema.json can be found [here](https://github.com/CsteerDevops1/wiki-framework/blob/develop/coreService/schema.json)
