### ISSUE TITLE
Add script which will add EN-RU translations to each word in DB.

### ISSUE THREAD

**Issue by orasul** [CsteerDevops1/wiki-framework#20]
Subject.
Best way is to use googe translate public API. Don't forget to add 1 sec sleep to avoid bans from google.

**Comment by Raxel55** [comment]
I will add new field russian_description to DB and make the translator translate description too

**Comment by orasul** [comment]
Please add description of the process to https://github.com/CsteerDevops1/wiki-framework/wiki/User-Acceptance-Test#cron-translator

**Comment by Raxel55** [comment]
I added the description of the translation process to wiki-page. Please check, @orasul
