### ISSUE TITLE
Core service which will store and provide data in and from data storage. It should check that any data which is going to be saved first should be checked with schema.

### ISSUE THREAD

**Issue by takikokos** [CsteerDevops1/wiki-framework#8]
It should provide API for adding data and for retrieving it from storage.

**Comment by orasul** [comment]
Core service should provide well-documented, simple API for other components:
GET - get list of words in db, get particular word data, etc.
POST - add new word (with all data, checked with schema).
PUT - update existing word data.
DELETE - remove word.
Successful operations should result in updating database contents.

**Comment by takikokos** [comment]
[Done](https://github.com/CsteerDevops1/wiki-framework/wiki/API)
