### ISSUE TITLE
Create a table to store users with their roles in mongo

### ISSUE THREAD

**Issue by Esclide** [CsteerDevops1/wiki-framework#83]
Two types of roles:
-user can edit unstable objects, delete and add new ones
-admin have all the users possibilities, but also he can change 'stable' property to 'unstable' and vice versa

**Comment by orasul** [comment]
One more idea.
There should be 3 permissions levels: admins, users and guests.
Each account which was authenticated by web ui auth process or via tg-loginname should automatically become guest. Guests - should be the straightforward way of adding new users in database.
Admins should be able to grant permission level to any user.
